[build]
builder = "NIXPACKS"

[deploy]
# Para frontend
[[services]]
name = "victorious-empathy"
build = { root = "frontend", command = "npm run build" }
start = "npm start"
env = { NODE_ENV = "production" }
