"""Create Database

Revision ID: 852d7286c972
Revises: 031a6b2fada8
Create Date: 2025-09-03 17:50:45.092062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '852d7286c972'
down_revision: Union[str, Sequence[str], None] = '031a6b2fada8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Perfil_Habilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Perfil_id', sa.Integer(), nullable=True),
    sa.Column('habilidad_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('OFRECE', 'BUSCA', name='tipoenum'), nullable=True),
    sa.Column('nivel', sa.Enum('PRINCIPIANTE', 'INTERMEDIO', 'EXPERTO', name='nivelenum'), nullable=True),
    sa.ForeignKeyConstraint(['Perfil_id'], ['perfiles.id'], ),
    sa.ForeignKeyConstraint(['habilidad_id'], ['habilidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('perfil_habilidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_habilidad',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Perfil_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('habilidad_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tipo', mysql.ENUM('OFRECE', 'BUSCA'), nullable=True),
    sa.Column('nivel', mysql.ENUM('PRINCIPIANTE', 'INTERMEDIO', 'EXPERTO'), nullable=True),
    sa.ForeignKeyConstraint(['Perfil_id'], ['perfiles.id'], name=op.f('perfil_habilidad_ibfk_1')),
    sa.ForeignKeyConstraint(['habilidad_id'], ['habilidad.id'], name=op.f('perfil_habilidad_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Perfil_Habilidad')
    # ### end Alembic commands ###
